association:
    resource: "@AssociationBundle/Resources/config/routing.yml"
    prefix:   /association

benevole:
    resource: "@BenevoleBundle/Resources/config/routing.yml"
    prefix:   /benevole

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

necessiteux:
    resource: "@NecessiteuxBundle/Resources/config/routing.yml"
    prefix:   /necessiteux

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
login:
    path: /login
    defaults:
        _controller: AppBundle:Controller:DefaultController
        template:    login.html.twig
register:
    path: /register
    defaults:
         _controller: AppBundle:Controller:DefaultController
         template:    register.html.twig

user_homepage:
    path: /user_homepage
    defaults:
        _controller: AppBundle:Controller:DefaultController
        template:    index2.html.twig