association_homepage:
    path:     /
    defaults: { _controller: AssociationBundle:Default:index }

show_all:
    path:     /showAll
    defaults: { _controller: AssociationBundle:campement:showAll }


show_mine:
    path:     /showMine
    defaults: { _controller: AssociationBundle:campement:showMine }

edit:
    path:     /edit/{id}
    defaults: { _controller: AssociationBundle:campement:edit }

create:
    path:     /create
    defaults: { _controller: AssociationBundle:campement:create }
delete:
    path:     /delete/{id}
    defaults: { _controller: AssociationBundle:campement:delete }
takeCharge:
    path:     /takeCharge/{id}
    defaults: { _controller: AssociationBundle:campement:takeCharge }