showAllMobile:
  path:     /showAllMobile
  defaults: { _controller: AssociationBundle:evenement:showAllMobile }

showMyMobile:
  path:     /showMyMobile
  defaults: { _controller: AssociationBundle:evenement:showMyMobile }
newMobile:
  path:     /newMobile
  defaults: { _controller: AssociationBundle:evenement:newMobile }

deleteMobile:
  path:  /deleteMobile/{id}
  defaults: { _controller: AssociationBundle:evenement:deleteMobile }

EditEventMobile:
  path:  /EditEventMobile
  defaults: { _controller: AssociationBundle:evenement:EditEventMobile }

FeedBackMobile:
  path:  /FeedBackMobile/{id}
  defaults: { _controller: AssociationBundle:evenement:FeedBackMobile }
allmobile:
  path:     /allmobile
  defaults: { _controller: AssociationBundle:campement:allmobile }
deletecCmpMobile:
  path:     /deletecCmpMobile
  defaults: { _controller: AssociationBundle:campement:deletecCmpMobile }
showmineMobile:
  path:     /showmineMobile
  defaults: { _controller: AssociationBundle:campement:showmineMobile }
nontakeChargeMobileMoblie:
  path:     /nontakeChargeMobileMoblie
  defaults: { _controller: AssociationBundle:campement:nontakeChargeMobileMoblie }
updateCampMobile:
  path:     /updateCampMobile
  defaults: { _controller: AssociationBundle:campement:updateCampMobile }
newAction:
  path:     /newmobile
  defaults: { _controller: AssociationBundle:campement:newMobile }

takeChargeMobile:
  path:     /takeChargeMobileAction
  defaults: { _controller: AssociationBundle:campement:takeChargeMobile }
findmobile:
  path:     /findmobile/{id}
  defaults: { _controller: AssociationBundle:campement:findMobile }

association_homepage:
  path:     /
  defaults: { _controller: AssociationBundle:Default:index }

show_all:
  path:     /showAll
  defaults: { _controller: AssociationBundle:campement:showAll }


show_mine:
  path:     /showMine
  defaults: { _controller: AssociationBundle:campement:showMine }

editcamp:
  path:     /editcampement/{id}
  defaults: { _controller: AssociationBundle:campement:edit }
pdfcampement:
  path:     /pdfCampement/{id}
  defaults: { _controller: AssociationBundle:campement:pdfCampement }

createcamp:
  path:     /create
  defaults: { _controller: AssociationBundle:campement:create }
deletecamp:
  path:     /delete/{id}
  defaults: { _controller: AssociationBundle:campement:delete }
takeCharge:
  path:     /takeCharge/{id}
  defaults: { _controller: AssociationBundle:campement:takeCharge }
nontakeCharge:
  path:     /nontakeCharge/{id}
  defaults: { _controller: AssociationBundle:campement:nontakeCharge }
contact:
  path:     /contact
  defaults: { _controller: AssociationBundle:campement:contact }
ajax_search:
  path:     /search
  defaults: { _controller: AssociationBundle:campement:search }

recherche:
  path:     /camps
  defaults: { _controller: AssociationBundle:campement:recherche}

new:
  path:     /new
  defaults: { _controller: AssociationBundle:evenement:new }

deleteevent:
  path:     /deleteevent/{id}
  defaults: { _controller: AssociationBundle:evenement:delete }

editevent:
  path:     /editevent/{id}
  defaults: { _controller: AssociationBundle:evenement:edit }

show:
  path:   /show
  defaults: {_controller: AssociationBundle:evenement:show}

show_My:
  path:   /showMyEvent
  defaults: {_controller: AssociationBundle:evenement:showMyEvent}

benevole:
  path: /benevole/{id}
  defaults: {_controller: AssociationBundle:evenement:showBenevole}
don:
  path: /don/{id}
  defaults: {_controller: AssociationBundle:evenement:showDon}

deleteDon:
  path:     /deleteDon/{id}
  defaults: { _controller: AssociationBundle:evenement:deleteDon }

pdfevent:
  path:     /showPdf
  defaults: { _controller: AssociationBundle:evenement:showPdf }


mail:
  path:     /sendMail
  defaults: { _controller: AssociationBundle:evenement:sendMail }

feedBack:
  path:     /FeedBack/{id}
  defaults: { _controller: AssociationBundle:evenement:FeedBack }

notifications:
  path: /notifications
  defaults:
    _controller: NecessiteuxBundle:Notification:display

demandes:
  path: /demandes
  defaults:
    _controller: NecessiteuxBundle:demandeAide:readAssociation

readnotif:
  path: /readnotif/{id}
  defaults:
    _controller: NecessiteuxBundle:demandeAide:readnotif

homeasso:
  path: /home
  defaults:
    _controller: AssociationBundle:Default:index


showmobile:
  path:     /showmobile/{id}
  defaults: { _controller: AssociationBundle:campement:showmobile }
