necessiteux_homepage:
    path:     /
    defaults: { _controller: NecessiteuxBundle:Default:index }

requests:
    path: /read
    defaults:
        _controller: NecessiteuxBundle:demandeAide:read

create:
    path: /create
    defaults:
        _controller: NecessiteuxBundle:demandeAide:create

update:
    path: /update/{id}
    defaults:
        _controller: NecessiteuxBundle:demandeAide:update

delete:
    path: /delete/{id}
    defaults:
        _controller: NecessiteuxBundle:demandeAide:delete



confirmRequestMobile:
    path: /confirmRequestMobile/{id}
    defaults:
        _controller: NecessiteuxBundle:demandeAide:confirmRequestMobile
PDF:
    path: /pdf
    defaults:
        _controller: NecessiteuxBundle:demandeAide:generate_pdf

create2:
    path: /create2
    defaults:
        _controller: NecessiteuxBundle:Feedback:create

feedbacks:
    path: /read2
    defaults:
        _controller: NecessiteuxBundle:Feedback:read

update2:
    path: /update2/{id}
    defaults:
        _controller: NecessiteuxBundle:Feedback:update

delete2:
    path: /delete2/{id}
    defaults:
        _controller: NecessiteuxBundle:Feedback:delete

AllRequestsMobile:
    path: /allrequestsMobile
    defaults:
        _controller: NecessiteuxBundle:demandeAide:AllRequestsMobile

addRequestMobile:
    path: /addRequestMobile
    defaults:
        _controller: NecessiteuxBundle:demandeAide:addRequestMobile

findRequestMobile:
    path: /findRequestMobile/{id}
    defaults:
        _controller: NecessiteuxBundle:demandeAide:findRequestMobile

updateRequestMobile:
    path: /updateRequestMobile/{id}
    defaults:
        _controller: NecessiteuxBundle:demandeAide:updateRequestMobile

deleteRequestMobile:
    path: /deleteRequestMobile/{id}
    defaults:
        _controller: NecessiteuxBundle:demandeAide:deleteRequestMobile

AllFeedbacksMobile:
    path: /allfeedbacksMobile
    defaults:
        _controller: NecessiteuxBundle:Feedback:AllFeedbackMobile

addFeedbackMobile:
    path: /addFeedbackMobile
    defaults:
        _controller: NecessiteuxBundle:Feedback:addFeedbackMobile

findFeedbackMobile:
    path: /findFeedbackMobile/{id}
    defaults:
        _controller: NecessiteuxBundle:Feedback:findFeedbackMobile

updateFeedbackMobile:
    path: /updateFeedbackMobile/{id}
    defaults:
        _controller: NecessiteuxBundle:Feedback:updateFeedbackMobile

deleteFeedbackMobile:
    path: /deleteFeedbackMobile/{id}
    defaults:
        _controller: NecessiteuxBundle:Feedback:deleteFeedbackMobile


confirm:
    path:   /{id}/confirm
    defaults:
        _controller: NecessiteuxBundle:demandeAide:confirm
